import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Google_Sans_Flex } from 'next/font/google';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});
const googleSansFlex = Google_Sans_Flex({
  subsets: ['latin'],
  weight: 'variable',
  variable: '--font-num',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${googleSansFlex.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
